# https://stackoverflow.com/questions/49316050/how-to-deal-semantic-versioning-on-jenkins#49329647
# https://github.com/marketplace/actions/tag-release-on-push-action
# https://github.com/marketplace/actions/git-semantic-version
# https://github.com/marketplace/actions/upload-artifact
# https://github.com/marketplace/actions/download-artifact
name: Build
on: push

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Install Yarn
        run: npm install -g yarn
      - name: Yarn Install
        run: yarn install --frozen-lockfile
      # Get current builds version
      # Apply version to `package.json`
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
      # Upload build artifact
      # - uses: actions/upload-artifact

  # release:
  #   runs-on: ubuntu-latest
  #   on:
  #     push:
  #       branches:
  #         - master
  #   env:
  #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #   steps:
  #     - uses: actions/download-artifact
  #     - uses: rymndhng/tag-release-on-push-action
  #       with:
          # strategy: patch
